version: '3.9'

services:
  backend:
    build: ./api
    container_name: ucis-backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENV=dev

  frontend:
    build: ./frontend
    container_name: ucis-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
